# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=32, verbose_name='Typ operacji')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Liczba żetonów')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Operacje na koncie',
                'verbose_name': 'operacja na koncie',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Kwota')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Czy oplacono')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Data opłacenia')),
            ],
            options={
                'verbose_name_plural': 'Rachunki',
                'verbose_name': 'rachunek',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Tekst')),
                ('rate', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Ocena')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywny')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Komentarze',
                'verbose_name': 'komentarz',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł')),
                ('short_description', models.CharField(max_length=255, verbose_name='Krótki opis')),
                ('long_description', models.TextField(max_length=2048, verbose_name='Długi opis')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveSmallIntegerField(verbose_name='Cena za 15min')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Lekcje',
                'ordering': ['-create_date'],
                'verbose_name': 'Lekcja',
            },
        ),
        migrations.CreateModel(
            name='LessonMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Lesson', verbose_name='Lekcja')),
            ],
            options={
                'verbose_name_plural': 'Zapisy na lekcje',
                'ordering': ['-create_date'],
                'verbose_name': 'zapis na lekcje',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł')),
                ('text', models.TextField(max_length=1024, verbose_name='Tekst')),
                ('is_read', models.BooleanField(default=False, verbose_name='Czy odczytane')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['-create_date'],
                'verbose_name': 'Wiadomość',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł')),
                ('text', models.CharField(max_length=255, verbose_name='Tekst')),
                ('type', models.CharField(choices=[('INVITE', 'INVITE'), ('TEACHER_UNSUBSCRIBE', 'TEACHER_UNSUBSCRIBE'), ('STUDENT_UNSUBSCRIBE', 'STUDENT_UNSUBSCRIBE'), ('SUBSCRIBE', 'SUBSCRIBE'), ('COMMENT', 'COMMENT'), ('NEW_BILL', 'NEW_BILL'), ('PAID_BILL', 'PAID_BILL'), ('DELETE_BILL', 'DELETE_BILL')], max_length=32, verbose_name='Typ')),
                ('data', models.CharField(blank=True, max_length=64, null=True, verbose_name='Dane')),
                ('is_read', models.BooleanField(default=False, verbose_name='Czy odczytane')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-create_date'],
                'verbose_name': 'Powiadomienie',
            },
        ),
        migrations.CreateModel(
            name='ReportedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Tekst zgłoszenia')),
                ('is_pending', models.BooleanField(default=True, verbose_name='Czy oczekujący')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Zgłoszone komentarze',
                'verbose_name': 'zgłoszenie komentarza',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Klucz')),
                ('is_open', models.BooleanField(default=True, verbose_name='Czy otwarty')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Lesson', verbose_name='Lekcja')),
            ],
            options={
                'verbose_name_plural': 'Pokoje konwersacji',
                'verbose_name': 'pokój konwersacji',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name_plural': 'Poziomy',
                'verbose_name': 'Poziom',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name_plural': 'Przedmioty',
                'verbose_name': 'Przedmiot',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('is_teacher', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='photos')),
                ('tokens', models.PositiveIntegerField(default=0, verbose_name='Żetony')),
                ('headline', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nagłówek')),
                ('biography', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Biografia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name_plural': 'Profile użytkowników',
                'verbose_name': 'Profil użytkownika',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Uczeń'),
        ),
        migrations.AddField(
            model_name='reportedcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Autor zgłoszenia'),
        ),
        migrations.AddField(
            model_name='reportedcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Comment', verbose_name='Komentarz'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Odbiorca'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recivers', to='koreline.UserProfile', verbose_name='Odbiorca'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='koreline.UserProfile', verbose_name='Nadawca'),
        ),
        migrations.AddField(
            model_name='lessonmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Uczeń'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Stage', verbose_name='Poziom'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Subject', verbose_name='Przedmiot'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Nauczyciel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='koreline.UserProfile', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='koreline.UserProfile', verbose_name='Nauczyciel'),
        ),
        migrations.AddField(
            model_name='bill',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Lesson', verbose_name='Lekcja'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Odbiorca'),
        ),
        migrations.AddField(
            model_name='accountoperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Uzytkownik'),
        ),
    ]
