# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0002_auto_20161114_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name_plural': 'Przedmioty',
                'verbose_name': 'Przedmiot',
            },
        ),
    ]
