# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koreline.Subject', verbose_name='Przedmiot'),
            preserve_default=False,
        ),
    ]
