# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0004_lesson_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Cena za 15min'),
            preserve_default=False,
        ),
    ]
