# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0006_userprofile_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos'),
        ),
    ]
