# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0007_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Żetony'),
        ),
    ]
