# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0008_userprofile_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Poziom',
                'verbose_name_plural': 'Poziom',
            },
        ),
    ]
