# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0009_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koreline.Stage', verbose_name='Poziom'),
            preserve_default=False,
        ),
    ]
