# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0012_auto_20161126_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmembership',
            options={'ordering': ['-create_date'], 'verbose_name': 'zapis na lekcje', 'verbose_name_plural': 'Zapisy na lekcje'},
        ),
        migrations.AddField(
            model_name='lessonmembership',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
    ]
