# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0014_room_roommember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='roommember',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'pokój konwersacji', 'verbose_name_plural': 'Pokoje konwersacji'},
        ),
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Uczeń'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
