# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0015_auto_20161206_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
