# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0017_remove_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Klucz'),
        ),
    ]
