# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0018_room_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Klucz'),
        ),
    ]
