# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Tekst')),
                ('rate', models.SmallIntegerField(verbose_name='Ocena')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywny')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Komentarze',
                'verbose_name': 'komentarz',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł')),
                ('text', models.TextField(max_length=1024, verbose_name='Tekst')),
                ('is_read', models.BooleanField(default=False, verbose_name='Czy odczytane')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['-create_date'],
                'verbose_name': 'Wiadomość',
            },
        ),
        migrations.CreateModel(
            name='RaportedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Tekst zgłoszenia')),
                ('is_pending', models.BooleanField(default=True, verbose_name='Czy oczekujący')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name_plural': 'Zgłoszone komentarze',
                'verbose_name': 'zgłoszenie komentarza',
            },
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Poziom', 'verbose_name_plural': 'Poziomy'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='long_description',
            field=models.TextField(default='Long desc', max_length=2048, verbose_name='Długi opis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(default='Short desc', max_length=255, verbose_name='Krótki opis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Dane'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVITE', 'INVITE'), ('TEACHER_UNSUBSCRIBE', 'TEACHER_UNSUBSCRIBE'), ('STUDENT_UNSUBSCRIBE', 'STUDENT_UNSUBSCRIBE'), ('SUBSCRIBE', 'SUBSCRIBE')], default='INVITE', max_length=32, verbose_name='Typ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nagłówek'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='raportedcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Autor zgłoszenia'),
        ),
        migrations.AddField(
            model_name='raportedcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.Comment', verbose_name='Komentarz'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recivers', to='koreline.UserProfile', verbose_name='Odbiorca'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='koreline.UserProfile', verbose_name='Nadawca'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='koreline.UserProfile', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='koreline.UserProfile', verbose_name='Nauczyciel'),
        ),
    ]
