# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0022_auto_20170104_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaportedComment',
            new_name='ReportedComment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVITE', 'INVITE'), ('TEACHER_UNSUBSCRIBE', 'TEACHER_UNSUBSCRIBE'), ('STUDENT_UNSUBSCRIBE', 'STUDENT_UNSUBSCRIBE'), ('SUBSCRIBE', 'SUBSCRIBE'), ('COMMENT', 'COMMENT')], max_length=32, verbose_name='Typ'),
        ),
    ]
