# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0023_auto_20170105_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia'),
        ),
    ]
