# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0024_auto_20170106_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=32, verbose_name='Typ operacji')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Liczba żetonów')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koreline.UserProfile', verbose_name='Uzytkownik')),
            ],
        ),
    ]
