# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koreline', '0027_auto_20170113_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='pay_date',
            new_name='paid_date',
        ),
    ]
